replicaCount: 1

image:
  repository: quay.io/docling-project/docling-serve
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5001

resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  allowPrivilegeEscalation: false
