{{- range $key, $secret := .Values.secrets }}
{{- if not (empty $secret.value) }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $key }}
data:
  {{ $secret.env }}: {{ $secret.value | b64enc | quote }}
type: Opaque
{{- end }}
{{- end }}