# Default values for pgvector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/pgvector/pgvector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: pg17

imagePullSecrets: []

nameOverride: "pgvector"
fullnameOverride: "pgvector"

serviceAccount:
  create: false

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5432

env:
  - name: POSTGRES_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: vectordb-app
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: vectordb-app
  - name: PGVECTOR_DBNAME
    valueFrom:
      secretKeyRef:
        key: dbname
        name: vectordb-app

resources: {}

autoscaling:
  enabled: false

volumeClaimTemplates:
  - metadata:
      name: pg-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi

volumeMounts:
  - mountPath: /var/lib/postgresql
    name: pg-data

nodeSelector: {}
affinity: {}
